[package]
name = "exam-viewer"
version = "0.1.0"
authors = ["Victor Panayotov <victorpanayotov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
